---
- hosts: all 
  user: root
  vars_files:
    - /root/ansible/vars/vars.yml
  tasks:
    - stat: path=/root/test.txt
      register: f
    - debug: msg="File exists. "
      when: f.stat.exists
    - debug: msg="File not exists."
      when: not f.stat.exists
    - name: copy .bashrc 
      shell: mv /root/.bashrc /root/.bashrc.back 
      when: f.stat.exists

