- name: git clone
  git: repo=https://github.com/aki01/bashrc.git dest={{ repos_dir }} version={{ branch }}

- name: mv .bashrc .bashrc.back
  shell: mv {{ work_dir }}/.bashrc {{ work_dir }}/.bashrc.back

- name: copy .bashrc
#  shell: mv {{ work_dir }}/.bashrc {{ work_dir }}/.bashrc.back
  shell: ln -s {{ repos_dir }}/bashrc {{ work_dir }}/.bashrc

- name: source .bashrc
  shell: source {{ work_dir }}/.bashrc
