- name: Build docker images from dockerfiles
  docker_image:
    name: ubuntu 
    path: /root/dockerfiles/ubuntu
#    state: build
#    tag: "cent"

- name: Run container
  docker:
    image: ubuntu 
    name: ubutnu 
#    state: present
    state: started
