- name: yum update
  yum: name=* state=latest
- name: install docker package(rhep)
  yum: name={{item}} state=installed
  with_items:
    - docker
  when: ansible_os_family == 'RedHat'
- name: install packages
  apt : name=* state=latest 
  when: ansible_os_family == 'Debian'
