- name: yum update
  yum: name=* state=latest
  when: ansible_os_family == 'RedHat'
- name: install docker package(rhep)
  yum: name={{item}} state=installed
  with_items:
    - python
    - python-devel
    - docker
  when: ansible_os_family == 'RedHat'
#- name: install pip(rhep)
#  command: easy_install pip
#  when: ansible_os_family == 'RedHat'
- name: install pip(rhep)
  yum: name=python-pip state: present
  when: ansible_os_family == 'RedHat'

- name: apt-get update
  apt: name=* state=latest
  when: ansible_os_family == 'Debian'  
- name: install packages
  apt : name={{item}} state=installed
  with_items:
    - python
    - python-devel
    - docker-io 
  when: ansible_os_family == 'Debian'

- name: Install Docker Python library
  pip: name={{ item }} state=present
  with_items:
    - docker-py==1.2.3
    - six>=1.4.0
  sudo: yes

- name: git clone 
  git: repo=https://github.com/aki01/dockerfiles.git dest={{ repos_dir }} version={{ branch }} update=yes 

