---
- name: Install dependencies
  become: yes
  yum: pkg={{item}} state=latest
  with_items:
    - git
    - tar
    - gcc
    - make
    - libffi-devel
    - zlib-devel
    - openssl-devel
    - readline-devel


- name: Install ruby
  become: yes
  yum: name=ruby state=latest

- name: Install rbenv
  become: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv_root }}

- name: Install ruby-build
  become: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build

- name: create rbenv group
  become: yes
  group: name=rbenv state=present

- name: add user to rbenv group
  become: yes
  user: name=centos append=yes groups=rbenv
  register: add_group

- name: create shims dir
  become: yes
  file: path={{ rbenv_root }}/shims state=directory

- name: create versions dir
  become: yes
  file: path={{ rbenv_root }}/versions state=directory

- name: change owner of install dir
  become: yes
  command: chgrp -R rbenv {{ rbenv_root }}

- name: change mode of install dir
  become: yes
  command: chmod -R g+rwxXs {{ rbenv_root }}

- name: Set rbenv env file
  become: yes
  copy: src=rbenv.sh dest=/etc/profile.d mode=0775

- name: Install ruby with rbenv
  shell: bash -lc "CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ ruby_version }}"

- name: "set ruby {{ ruby_version }} for system"
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"

